# Generated by Django 4.2.2 on 2023-06-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_wishlist_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='products.product'),
        ),
    ]
