# Generated by Django 4.2.2 on 2023-06-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_wishlist_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='name',
            field=models.CharField(default='mywish', max_length=250),
            preserve_default=False,
        ),
    ]
